### ISSUE TITLE
Json API for product id's

### ISSUE THREAD

**Issue by AroPix** [JicuNull/MCReverse#12]
Hey,
Im using your backend (mccoupon.deals) to generate codes via a discord bot, and im developing a android app right now. The problem is that i right now need to scrape your page, it would be neat and beneficial if there would be some kind of json api, listing all active products with ids, the image url and the product description. It drove me crazy today, that my code wasnt working properly, until i realized that you redirected the site to your dev subdomain xD.
Also is there any way of contacting you through as example Discord or Matrix?
Greetings AroPix :)

**Comment by Louuke** [comment]
Recently I have rewritten most of the code in the backend and am still trying to resolve some issues. Therefore I am also redirecting to the dev server.

I can probably help you with the API. You can write me on Discord.
