### ISSUE TITLE
Coupons not accepted 

### ISSUE THREAD

**Issue by DanBeast1337** [JicuNull/MCReverse#2]
When entering any code from the website at the terminal, it throws an error, exactly as if the code wouldn't exist.

Didn't work at three different McDonald's, at the different times today.

**Comment by Louuke** [comment]
Hello,

nice that you have tried the site.
That the coupons didn't work is actually very strange, as numerous coupons were successfully redeemed yesterday and everything looks normal today as well.
Nevertheless, I have now restarted the service.

You are trying it in Germany, right? The project is designed exclusively for this region.

I may try it again myself tomorrow evening.

**Comment by DanBeast1337** [comment]
Yeah, I also used it the day before with no issue whatsoever, thanks for the milkshakes. :D 

I tried it yesterday (30) again and no matter if in Munich (twice, two different ones) or Landshut, it wouldn't accept the codes. 

I will try later today again as well and report.

**Comment by DanBeast1337** [comment]
Tried it yesterday and it worked again, with no issue. Thanks! 

So maybe, just in case, add a regular restart every now and then?

**Comment by Louuke** [comment]
Glad to hear it worked. I'm afraid I absolutely don't know why it suddenly stopped working.

When I have some time I might go through the code again and have a look. 

I will not do a restart automatically, but you can yell if something goes wrong :)

**Comment by Louuke** [comment]
You're right. No new codes were generated after midnight, that is, after new offers were rolled out.

I'll have to look at that later.

**Comment by DanBeast1337** [comment]
I thought it was something like that. It's weird though, that there were "new" codes generated, which weren't valid though. 

Thank you however for looking into it deeper!

**Comment by DanBeast1337** [comment]
For reference, leaving the pics here. Happened again today (0:27)

![IMG_20220404_002751](https://user-images.githubusercontent.com/9980963/161451441-5ec9f7f0-2cb9-498f-a91a-d55a1583efe0.jpg)
![IMG_20220404_002658](https://user-images.githubusercontent.com/9980963/161451444-73c632a3-dfc7-411d-962f-66fa198f3a6f.jpg)
![IMG_20220404_002702](https://user-images.githubusercontent.com/9980963/161451447-b3f4bc22-654b-42c6-b258-ae6e67785b62.jpg)

**Comment by Louuke** [comment]
I recently made a couple of changes and I believe the error is fixed. At least the problem didn't occure for the last few days.

Anyways, I will keep this open for a little longer, just in case.
