### ISSUE TITLE
Free BigMac Coupons not present anymore.

### ISSUE THREAD

**Issue by AroPix** [JicuNull/MCReverse#3]
At first, thanks for your project, i really like it and i implemented your website into my private discord bot (i hope its fine). But i wanted to ask if there is a reason for the free Big Macs not being present anymore. Did they patch it?
Thanks for your beautiful project tho!
Would contribute but they only language i can really read is python :)

**Comment by Louuke** [comment]
Hey, glad to hear you like my project.

No problem, feel free to use my site however you like. Note, however, that I can't guarantee you that I won't break something in the future that might affect your bot.

The free coupons were unfortunately just a short-lived promotion that has been over for just under a week. I will work on increasing the number of coupons further though.

Python is also a cool language, but unfortunately I had never really gotten into it in depth.
