### ISSUE TITLE
Polish version

### ISSUE THREAD

**Issue by akwav** [JicuNull/MCReverse#4]
Hi, I wanted to sniff Polish version of the app. Unfortunately, it is protected against such tries. Could You give me an idea how to bypass it?

**Comment by Louuke** [comment]
You could try to patch the app using [Apk-Mitm](https://github.com/shroudedcode/apk-mitm) and mitmproxy.
If that's not working, because the app craches, you could take a look at frida

**Comment by akwav** [comment]
thx

**Comment by Louuke** [comment]
np :)
